# Generated by Django 5.0.3 on 2024-04-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='FirstName',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='users',
            name='SecondName',
            field=models.CharField(default='', max_length=50),
        ),
    ]
