# Generated by Django 5.0.3 on 2024-04-29 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0004_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tables_Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Restaurant.restaurant')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Restaurant.table')),
            ],
        ),
    ]
