# Generated by Django 5.0.3 on 2024-04-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='priority',
            field=models.CharField(choices=[(1, 'High'), (2, 'Medium'), (3, 'Low')], default=3, max_length=6),
        ),
    ]
